services:
  - type: web
    name: college-management-system
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn college_management_system.wsgi
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "college-management-system.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: college-db
          property: connectionString

databases:
  - name: college-db
    plan: free
